### ISSUE TITLE
Building for Windows 7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jtsiomb/stereowrap#6]
```
How do I build this under Windows 7 64bit?
```

Original issue reported on code.google.com by `vernehml...@googlemail.com` on 11 Sep 2013 at 8:15

**Comment by oldyz2** [comment]
i downloaded github desktop, git, the instructions given for making a build seem insuficient for windows, i cant even open the repository, both programs tell me there is an error or that is not a repository, so i dont understand how to do the make or make install commands

**Comment by jtsiomb** [comment]
Stereowrap doesn't support on windows. It's an LD_PRELOADable wrapper for UNIX systems with X11 and GLX.
